# Generated by Django 2.2.4 on 2019-09-18 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDfkx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=255, unique=True)),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '地方科协',
                'verbose_name_plural': '地方科协',
                'db_table': 'agency_dfkx',
            },
        ),
        migrations.CreateModel(
            name='AgencyJg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=255, unique=True)),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '科协机关及事业单位',
                'verbose_name_plural': '科协机关及事业单位',
                'db_table': 'agency_jg',
            },
        ),
        migrations.CreateModel(
            name='AgencyQgxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=255, unique=True)),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '全国学会',
                'verbose_name_plural': '全国学会',
                'db_table': 'agency_qgxh',
            },
        ),
        migrations.CreateModel(
            name='ChinaTopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '中央领导人新闻',
                'verbose_name_plural': '中央领导人新闻',
                'db_table': 'chinaTopNews',
            },
        ),
        migrations.CreateModel(
            name='DFKX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '地方科协',
                'verbose_name_plural': '地方科协',
                'db_table': 'dfkx',
            },
        ),
        migrations.CreateModel(
            name='KX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '中国科协',
                'verbose_name_plural': '中国科协',
                'db_table': 'kx',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '时政要闻',
                'verbose_name_plural': '时政要闻',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='QGXH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '全国学会',
                'verbose_name_plural': '全国学会',
                'db_table': 'qgxh',
            },
        ),
        migrations.CreateModel(
            name='TECH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('hidden', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '科技热点',
                'verbose_name_plural': '科技热点',
                'db_table': 'tech',
            },
        ),
    ]
