# Generated by Django 2.2.4 on 2019-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0002_channeltodatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinatopnews',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
