# Generated by Django 2.2.4 on 2019-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0004_auto_20190920_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinatopnews',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kx',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
