# Generated by Django 2.2.4 on 2019-09-24 09:39

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0005_auto_20190923_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dfkx',
            options={'verbose_name': '地方科协新闻', 'verbose_name_plural': '地方科协新闻'},
        ),
        migrations.AlterModelOptions(
            name='kx',
            options={'verbose_name': '中国科协新闻', 'verbose_name_plural': '中国科协新闻'},
        ),
        migrations.AlterModelOptions(
            name='qgxh',
            options={'verbose_name': '全国学会新闻', 'verbose_name_plural': '全国学会新闻'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name': '科技热点新闻', 'verbose_name_plural': '科技热点新闻'},
        ),
        migrations.AddField(
            model_name='chinatopnews',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='dfkx',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='kx',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='news',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='qgxh',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='tech',
            name='my',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='添加文本', null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='agencydfkx',
            name='department',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='agencydfkx',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='agencyjg',
            name='department',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='agencyjg',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='agencyqgxh',
            name='department',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='agencyqgxh',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chinatopnews',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='kx',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='news',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='news',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='content',
            field=models.TextField(verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='hidden',
            field=models.BooleanField(blank=True, default=True, verbose_name='是否推送'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片集链接'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='today',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tech',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻url'),
        ),
    ]
