# Generated by Django 2.2.4 on 2019-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0006_auto_20190924_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinatopnews',
            name='my',
        ),
        migrations.RemoveField(
            model_name='dfkx',
            name='my',
        ),
        migrations.RemoveField(
            model_name='kx',
            name='my',
        ),
        migrations.RemoveField(
            model_name='news',
            name='my',
        ),
        migrations.RemoveField(
            model_name='qgxh',
            name='my',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='my',
        ),
    ]
