# Generated by Django 2.2.4 on 2019-09-24 16:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0008_auto_20190924_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinatopnews',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='http://127.0.0.1:8000/media/media/'), upload_to='media', verbose_name='图片'),
        ),
    ]
