# Generated by Django 2.2.4 on 2019-09-24 16:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuiJian', '0010_auto_20190924_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinatopnews',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='dfkx',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='kx',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='qgxh',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\推荐部署的新版本\\news\\kexie\\media\\media'), upload_to='mgh', verbose_name='图片'),
        ),
    ]
